### ISSUE TITLE
Support Service of type LoadBalancer to enable global load balancing on L4 

### ISSUE THREAD

**Issue by ytsarev** [AbsaOSS/k8gb#147]
Currently k8gb fully relies on underlying Ingress that it controls. It has limitations of exclusive http/https support so services on another ports and another protocols are not covered by Gslb operations.
We can change that by enabling k8gb to control underlying Service of type LoadBalancer. It will create mechanism to expose any tcp/udp service on any port and protocol. We definitely should keep current Ingress operations for L7 http/https .

Service enabled spec might look like:
```
apiVersion: k8gb.absa.oss/v1beta1
kind: Gslb
metadata:
  name: test-gslb
  namespace: test-gslb
spec:
  loadBalancer:
    host: app1.cloud.example.com
    serviceName: app # Service with type: LoadBalancer
  strategy:
    type: roundRobin
```

**Comment by abaguas** [comment]
During the contribfest today an additional usecase was pointed out for Services of type ClusterIP. In their setup the service IP addresses are routable in the WAN.

When implementing this feature we should support both services of type LoadBalancer and ClusterIP

**Comment by 13567436138** [comment]
```
cat << EOF | kubectl --kubeconfig ~/.kube/minio-01 apply -f - 
apiVersion: k8gb.absa.oss/v1beta1
kind: Gslb
metadata:
  name: minio-svc-gslb
  namespace: minio
spec:
  ingress:
    backend:
      service:
        name: minio
        port:
          number: 9000
  strategy:
    type: failover 
    primaryGeoTag: cn-hz
EOF

cat << EOF | kubectl --kubeconfig ~/.kube/minio-02 apply -f - 
apiVersion: k8gb.absa.oss/v1beta1
kind: Gslb
metadata:
  name: minio-svc-gslb
  namespace: minio
spec:
  ingress:
    backend:
      service:
        name: minio
        port:
          number: 9000

  strategy:
    type: failover 
    primaryGeoTag: cn-hz
EOF
```


when will this support ，I do not know how to loadbalancer tcp traffic
