### ISSUE TITLE
Oppertunity to enhance edgeDNSServer from single instance to multiple

### ISSUE THREAD

**Issue by jeffhelps** [AbsaOSS/k8gb#154]
This would allow in the use case where you may have more than 1 DNS server to query (for redundancy)

```
edgeDNSServer: &edgeDNSServer:
  - 1.1.1.1
  - 2.2.2.2 
```

**Comment by jkremser** [comment]
currently, the `edgeDNSServer` and `edgeDNSServerPort` are passed to operator as environment variables. 

```yaml
...
            - name: EDGE_DNS_SERVER
              value: {{ .Values.k8gb.edgeDNSServer }}
            - name: EDGE_DNS_SERVER_PORT
              value: "53"
...
```

If multiple edgeDNSServers should be supported, I'd suggest something like this:

```yaml
...
            - name: EDGE_DNS_SERVERS
              value: "1.1.1.1:53, 2.2.2.2, 3.3.3.3:1053"
...
```

so that the ip and port are bounded together and separated by the colon `:` with a rule, that if the port is missing it would default to `53`. Also the entries are separated by comma and the order matters (the server that's listed first is the primary one / first in the fallback mechanism)

As for the helm chart and the `values.yaml` it may look like this:

```yaml
edgeDNSServer: &edgeDNSServer:
  - 1.1.1.1
  - 2.2.2.2:1053 
  ```
 
then we can use:
`{{ join "," .Values.some.array }}`
at `chart/k8gb/operator.yaml`

Bad news is that it's a breaking change, the name that better represents the nature of the variable would be the plural form - i.e.  `s/EDGE_DNS_SERVER/EDGE_DNS_SERVERS/` + the  `EDGE_DNS_SERVER_PORT` variable is not needed anymore, because the port can be optionally passed in the `EDGE_DNS_SERVERS` comma-separated list itself.

if it makes sense, I can start working on this.
