### ISSUE TITLE
k8gb crashes on malformed spec section in `gslb` custom resource

### ISSUE THREAD

**Issue by somaritane** [AbsaOSS/k8gb#296]
When `gslb` spec contains wrong path section for `host:` rule e.g:

```
spec:
  ingress:
    rules:
    - host: host.examle.com
       https: <==== should be http instead!
         paths:
...
  strategy:
    dnsTtlSeconds: 30
    splitBrainThresholdSeconds: 300
    type: roundRobin
```

this leads to panic and k8g controller crash.
Following can be seen in k8gb log
```
E0212 07:54:49.306061       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
```
